2023-07-18 18:25:13,002 DEBUG utils.py Была вызвана функция get_message c параметрами (<socket.socket fd=692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64615)>,), {}. Вызов из модуля common.utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-18 18:25:13,003 DEBUG server.py Разбор сообщения от клиента : {'action': 'message', 'from': 'test3', 'to': 'test`', 'time': 1689693912.7581246, 'mess_text': 'Hello test1'}
2023-07-18 18:25:13,003 ERROR server.py Пользователь test` не зарегистрирован на сервере, отправка сообщения невозможна.
2023-07-18 18:25:50,534 DEBUG utils.py Была вызвана функция get_message c параметрами (<socket.socket fd=660, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64616)>,), {}. Вызов из модуля common.utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-18 18:25:50,534 DEBUG server.py Разбор сообщения от клиента : {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1689693950.4783068, 'mess_text': 'hello'}
2023-07-18 18:25:50,535 DEBUG utils.py Была вызвана функция send_message c параметрами (<socket.socket fd=696, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64614)>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1689693950.4783068, 'mess_text': 'hello'}), {}. Вызов из модуля common.utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-18 18:25:50,535 INFO server.py Отправлено сообщение пользователю test2 от пользователя test1.
2023-07-18 18:26:05,544 DEBUG utils.py Была вызвана функция get_message c параметрами (<socket.socket fd=660, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64616)>,), {}. Вызов из модуля common.utils. Вызов из функции self._bootstrap_inner().Вызов из функции run
2023-07-18 18:26:05,544 DEBUG server.py Разбор сообщения от клиента : {'action': 'message', 'from': 'test1', 'to': 'test3', 'time': 1689693965.3669255, 'mess_text': 'hello test3'}
2023-07-18 18:26:05,545 DEBUG utils.py Была вызвана функция send_message c параметрами (<socket.socket fd=692, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 64615)>, {'action': 'message', 'from': 'test1', 'to': 'test3', 'time': 1689693965.3669255, 'mess_text': 'hello test3'}), {}. Вызов из модуля common.utils. Вызов из функции self._bootstrap_inner().Вызов из функции process_message
2023-07-18 18:26:05,545 INFO server.py Отправлено сообщение пользователю test3 от пользователя test1.
